## Problem1

In [1]:
import numpy as np

In [ ]:
arr = [i+1 for i in range(30)]
arr = np.array(arr)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [11]:
newarr = arr.reshape(6 ,5)
newarr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
selected_part = newarr[ 2:4 , 0:2]
selected_part 

array([[11, 12],
       [16, 17]])

## Problem2

In [13]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

In [16]:
first50_primes = [i for i in range(1000) if is_prime(i)]

In [19]:
first50_primes[:50]

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97,
 101,
 103,
 107,
 109,
 113,
 127,
 131,
 137,
 139,
 149,
 151,
 157,
 163,
 167,
 173,
 179,
 181,
 191,
 193,
 197,
 199,
 211,
 223,
 227,
 229]

## Problem3

In [29]:
last_array = newarr[0:4 , 1:5]
print(last_array.diagonal())

[ 2  8 14 20]


## problem4

In [55]:
last = newarr[ 0:6, 3:5 ]
arr = [last[0] , last[4] , last[5]] 
arr = np.array(arr)
arr

array([[ 4,  5],
       [24, 25],
       [29, 30]])