# import necessary libraries 

In [17]:
import numpy as np
from itertools import product 

# define step function

In [18]:
def step(x):
    return 1 if x >= 0 else 0

# define nueron function 

In [19]:
def nueron(x , w , b):
    return step(x@w + b)

# define or gate logic

In [20]:
def or_gate(x):
    result = nueron(x , np.array([1,1]) , -1)
    return result

# define and gate logic

In [21]:
def and_gate(x):
    result = nueron(x , np.array([1,1]) , -2)
    return result

# define xor gate logic 

In [22]:
def xor_gate_method_1(x):
    n1 = nueron(x , np.array([-1,1]) , -1)
    n2 = nueron(x , np.array([1,-1]) , -1)
    n3 = or_gate(np.array([n1 , n2]))
    return n3 

In [23]:
def xor_gate_method_2(x):
    n1 = nueron(x , np.array([1,1]) , -1)
    n2 = nueron(x , np.array([-1,-1]) , 1)
    n3 = nueron(np.array([n1,n2]) , np.array([1,1]) , -2)
    return n3

# define multi layer perceptron logic

In [ ]:
# (a!xz or a!y) and (xy or !x!z)   ---> [a , x , y , z] ---> [0 ,1 ,2 ,3 ]  
def mlp(x):
    n1 = nueron(x[[0, 1, 3]], np.array([1, -1, 1]), -2)
    n2 = nueron(x[[0, 2]], np.array([1, -1]), -1)
    n3 = nueron(x[[1, 2]], np.array([1, 1]), -2)
    n4 = nueron(x[[1, 3]], np.array([1, 1]), -2)
    n5 = or_gate(np.array([n1, n2]))
    n6 = nueron(np.array([n3, n4]), np.array([1, -1]), 0)
    n7 = and_gate(np.array([n5, n6]))
    return n7

# define multi layer perceptron logic for testing 

In [25]:
def mlp_test(x):
    return ((x[0] and not x[1] and x[3]) or (x[0] and not x[2])) and ((x[1] and x[2]) or not (x[1] and x[3]))

# Test all the previous gates

### test mlp

In [26]:
x = [
    [a , x , y , z] for a in range(2)  for x in range(2)  for y in range(2)  for z in range(2)
 ]

s = '      '
print(f"MLP\t{s}value\ttest_value")
print("-" * 35)
x = np.array(x)
for c in x :
    my_result = mlp(c)
    test_result = mlp_test(c)
    print(f"{c}\t{my_result}\t{test_result}")


MLP	      value	test_value
-----------------------------------
[0 0 0 0]	0	0
[0 0 0 1]	0	0
[0 0 1 0]	0	0
[0 0 1 1]	0	0
[0 1 0 0]	0	0
[0 1 0 1]	0	0
[0 1 1 0]	0	0
[0 1 1 1]	0	0
[1 0 0 0]	1	True
[1 0 0 1]	1	True
[1 0 1 0]	0	False
[1 0 1 1]	1	True
[1 1 0 0]	1	True
[1 1 0 1]	0	False
[1 1 1 0]	0	False
[1 1 1 1]	0	False


### Test OR gate

In [27]:
x = [
    [x , y] for x in range(2) for y in range(2)
]

x = np.array(x)
print("OR GATE")
for c in x:
    result = or_gate(c)
    print(f"({c[0]} , {c[1]}) => {result}")

OR GATE
(0 , 0) => 0
(0 , 1) => 1
(1 , 0) => 1
(1 , 1) => 1


### Test And gate

In [28]:
x = [
    [x , y] for x in range(2) for y in range(2)
]

x = np.array(x)
print("AND GATE")
for c in x:
    result = and_gate(c)
    print(f"({c[0]} , {c[1]}) => {result}")

AND GATE
(0 , 0) => 0
(0 , 1) => 0
(1 , 0) => 0
(1 , 1) => 1


### Test XOR gate 

In [32]:
x = [
    [x , y] for x in range(2) for y in range(2)
]

x = np.array(x)
print("XOR GATE METHOD 1")
for c in x:
    result = xor_gate_method_1(c)
    print(f"({c[0]} , {c[1]}) => {result}")

XOR GATE METHOD 1
(0 , 0) => 0
(0 , 1) => 1
(1 , 0) => 1
(1 , 1) => 0


In [33]:
x = [
    [x , y] for x in range(2) for y in range(2)
]

x = np.array(x)
print("XOR GATE METHOD 2")
for c in x:
    result = xor_gate_method_2(c)
    print(f"({c[0]} , {c[1]}) => {result}")

XOR GATE METHOD 2
(0 , 0) => 0
(0 , 1) => 1
(1 , 0) => 1
(1 , 1) => 0
